<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-E9K3KF14" name="Default test" tests="2" failures="2" timestamp="7 May 2020 10:09:56 GMT" time="1.418" errors="0">
  <testcase name="feature" time="1.049" classname="testRunners.TestRunner">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at stepDefination.CreateCustomerApiStepDefination.i_set_a_valid_auth(CreateCustomerApiStepDefination.java:23)
	at ✽.I set a valid auth(./src/test/resources/featureFiles/ScanerioOutlineExample.feature:4)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="0.01" classname="testRunners.TestRunner">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at stepDefination.CreateCustomerApiStepDefination.i_set_a_valid_auth(CreateCustomerApiStepDefination.java:23)
	at ✽.I set a valid auth(./src/test/resources/featureFiles/ScanerioOutlineExample.feature:4)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
